### ISSUE TITLE
player list links missing userid

### ISSUE THREAD

**Issue by aletson** [aletson/votefinder-web#207]
the link to the players' posts doesn't have their id appended to the url, so they just link to the thread normally _- reported by Podima_

**Comment by rjmagley** [comment]
![image](https://user-images.githubusercontent.com/20324985/88336321-6533b800-ccfa-11ea-85cf-8a565f9ab884.png)

**Comment by rjmagley** [comment]
pretty sure the issue is in post_histories.html - looks like it's pulling `p.player.uid` instead of the new `p.player.sa_uid`. I don't currently have a DB that has all the new stuff in it so I can't try that out, but I'm 99% sure this is the issue. Spot-checked a few other games and the issue is the same there.

**Comment by aletson** [comment]
this is correct
